void Eff_CSC_ME13_SimHit()
{
//=========Macro generated from canvas: c/c
//=========  (Sun Sep 29 19:53:26 2019) by ROOT version 6.14/09
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(0.8571429,-0.15375,1.214286,1.1275);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.12);
   c->SetRightMargin(0.04);
   c->SetTopMargin(0.08);
   c->SetBottomMargin(0.12);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   
   TH1F *base__3 = new TH1F("base__3","",25,0.9,1.2);
   base__3->SetMinimum(0);
   base__3->SetMaximum(1.025);
   base__3->SetLineStyle(0);
   base__3->SetMarkerStyle(20);
   base__3->GetXaxis()->SetTitle("True muon |#eta|");
   base__3->GetXaxis()->SetLabelFont(42);
   base__3->GetXaxis()->SetLabelOffset(0.007);
   base__3->GetXaxis()->SetLabelSize(0.05);
   base__3->GetXaxis()->SetTitleSize(0.06);
   base__3->GetXaxis()->SetTitleOffset(0.9);
   base__3->GetXaxis()->SetTitleFont(42);
   base__3->GetYaxis()->SetTitle("Efficiency");
   base__3->GetYaxis()->SetLabelFont(42);
   base__3->GetYaxis()->SetLabelOffset(0.007);
   base__3->GetYaxis()->SetLabelSize(0.05);
   base__3->GetYaxis()->SetTitleSize(0.06);
   base__3->GetYaxis()->SetTitleOffset(0.9);
   base__3->GetYaxis()->SetTitleFont(42);
   base__3->GetZaxis()->SetLabelFont(42);
   base__3->GetZaxis()->SetLabelOffset(0.007);
   base__3->GetZaxis()->SetLabelSize(0.05);
   base__3->GetZaxis()->SetTitleSize(0.06);
   base__3->GetZaxis()->SetTitleFont(42);
   base__3->Draw("");
   TLatex *   tex = new TLatex(0.96,0.936,"14 TeV");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.936,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2208,0.936,"Simulation Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TEfficiency * den_clone3 = new TEfficiency("den_clone","",25,0.9,1.2);
   
   den_clone3->SetConfidenceLevel(0.6826895);
   den_clone3->SetBetaAlpha(1);
   den_clone3->SetBetaBeta(1);
   den_clone3->SetWeight(1);
   den_clone3->SetStatisticOption(0);
   den_clone3->SetPosteriorMode(0);
   den_clone3->SetShortestInterval(0);
   den_clone3->SetTotalEvents(0,0);
   den_clone3->SetPassedEvents(0,0);
   den_clone3->SetTotalEvents(1,0);
   den_clone3->SetPassedEvents(1,0);
   den_clone3->SetTotalEvents(2,0);
   den_clone3->SetPassedEvents(2,0);
   den_clone3->SetTotalEvents(3,0);
   den_clone3->SetPassedEvents(3,0);
   den_clone3->SetTotalEvents(4,0);
   den_clone3->SetPassedEvents(4,0);
   den_clone3->SetTotalEvents(5,0);
   den_clone3->SetPassedEvents(5,0);
   den_clone3->SetTotalEvents(6,0);
   den_clone3->SetPassedEvents(6,0);
   den_clone3->SetTotalEvents(7,0);
   den_clone3->SetPassedEvents(7,0);
   den_clone3->SetTotalEvents(8,0);
   den_clone3->SetPassedEvents(8,0);
   den_clone3->SetTotalEvents(9,0);
   den_clone3->SetPassedEvents(9,0);
   den_clone3->SetTotalEvents(10,0);
   den_clone3->SetPassedEvents(10,0);
   den_clone3->SetTotalEvents(11,0);
   den_clone3->SetPassedEvents(11,0);
   den_clone3->SetTotalEvents(12,0);
   den_clone3->SetPassedEvents(12,0);
   den_clone3->SetTotalEvents(13,0);
   den_clone3->SetPassedEvents(13,0);
   den_clone3->SetTotalEvents(14,0);
   den_clone3->SetPassedEvents(14,0);
   den_clone3->SetTotalEvents(15,0);
   den_clone3->SetPassedEvents(15,0);
   den_clone3->SetTotalEvents(16,0);
   den_clone3->SetPassedEvents(16,0);
   den_clone3->SetTotalEvents(17,0);
   den_clone3->SetPassedEvents(17,0);
   den_clone3->SetTotalEvents(18,0);
   den_clone3->SetPassedEvents(18,0);
   den_clone3->SetTotalEvents(19,0);
   den_clone3->SetPassedEvents(19,0);
   den_clone3->SetTotalEvents(20,0);
   den_clone3->SetPassedEvents(20,0);
   den_clone3->SetTotalEvents(21,0);
   den_clone3->SetPassedEvents(21,0);
   den_clone3->SetTotalEvents(22,0);
   den_clone3->SetPassedEvents(22,0);
   den_clone3->SetTotalEvents(23,0);
   den_clone3->SetPassedEvents(23,0);
   den_clone3->SetTotalEvents(24,0);
   den_clone3->SetPassedEvents(24,0);
   den_clone3->SetTotalEvents(25,0);
   den_clone3->SetPassedEvents(25,0);
   den_clone3->SetTotalEvents(26,0);
   den_clone3->SetPassedEvents(26,0);
   den_clone3->SetFillColor(19);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   den_clone3->SetLineColor(ci);
   den_clone3->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   den_clone3->SetMarkerColor(ci);
   den_clone3->SetMarkerStyle(21);
   den_clone3->Draw("same samep");
   
   TLegend *leg = new TLegend(0,0,0,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("den_clone","SimHits","pl");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TText *text = new TText(0.17,0.17,"ME1/3");
   text->SetNDC();
   text->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
