void Eff_ME11_LCT()
{
//=========Macro generated from canvas: c/c
//=========  (Tue Oct  1 15:41:07 2019) by ROOT version 6.14/09
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(1.371429,-0.15375,2.442857,1.1275);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.12);
   c->SetRightMargin(0.04);
   c->SetTopMargin(0.08);
   c->SetBottomMargin(0.12);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   
   TH1F *base__7 = new TH1F("base__7","",25,1.5,2.4);
   base__7->SetMinimum(0);
   base__7->SetMaximum(1.025);
   base__7->SetLineStyle(0);
   base__7->SetMarkerStyle(20);
   base__7->GetXaxis()->SetTitle("True muon |#eta|");
   base__7->GetXaxis()->SetLabelFont(42);
   base__7->GetXaxis()->SetLabelOffset(0.007);
   base__7->GetXaxis()->SetLabelSize(0.05);
   base__7->GetXaxis()->SetTitleSize(0.06);
   base__7->GetXaxis()->SetTitleOffset(0.9);
   base__7->GetXaxis()->SetTitleFont(42);
   base__7->GetYaxis()->SetTitle("Efficiency");
   base__7->GetYaxis()->SetLabelFont(42);
   base__7->GetYaxis()->SetLabelOffset(0.007);
   base__7->GetYaxis()->SetLabelSize(0.05);
   base__7->GetYaxis()->SetTitleSize(0.06);
   base__7->GetYaxis()->SetTitleOffset(0.9);
   base__7->GetYaxis()->SetTitleFont(42);
   base__7->GetZaxis()->SetLabelFont(42);
   base__7->GetZaxis()->SetLabelOffset(0.007);
   base__7->GetZaxis()->SetLabelSize(0.05);
   base__7->GetZaxis()->SetTitleSize(0.06);
   base__7->GetZaxis()->SetTitleFont(42);
   base__7->Draw("");
   TLatex *   tex = new TLatex(0.96,0.936,"14 TeV");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.936,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2208,0.936,"Simulation Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TEfficiency * den_clone7 = new TEfficiency("den_clone","",25,1.5,2.4);
   
   den_clone7->SetConfidenceLevel(0.6826895);
   den_clone7->SetBetaAlpha(1);
   den_clone7->SetBetaBeta(1);
   den_clone7->SetWeight(1);
   den_clone7->SetStatisticOption(0);
   den_clone7->SetPosteriorMode(0);
   den_clone7->SetShortestInterval(0);
   den_clone7->SetTotalEvents(0,0);
   den_clone7->SetPassedEvents(0,0);
   den_clone7->SetTotalEvents(1,0);
   den_clone7->SetPassedEvents(1,0);
   den_clone7->SetTotalEvents(2,0);
   den_clone7->SetPassedEvents(2,0);
   den_clone7->SetTotalEvents(3,0);
   den_clone7->SetPassedEvents(3,0);
   den_clone7->SetTotalEvents(4,0);
   den_clone7->SetPassedEvents(4,0);
   den_clone7->SetTotalEvents(5,0);
   den_clone7->SetPassedEvents(5,0);
   den_clone7->SetTotalEvents(6,0);
   den_clone7->SetPassedEvents(6,0);
   den_clone7->SetTotalEvents(7,0);
   den_clone7->SetPassedEvents(7,0);
   den_clone7->SetTotalEvents(8,0);
   den_clone7->SetPassedEvents(8,0);
   den_clone7->SetTotalEvents(9,0);
   den_clone7->SetPassedEvents(9,0);
   den_clone7->SetTotalEvents(10,0);
   den_clone7->SetPassedEvents(10,0);
   den_clone7->SetTotalEvents(11,0);
   den_clone7->SetPassedEvents(11,0);
   den_clone7->SetTotalEvents(12,0);
   den_clone7->SetPassedEvents(12,0);
   den_clone7->SetTotalEvents(13,0);
   den_clone7->SetPassedEvents(13,0);
   den_clone7->SetTotalEvents(14,0);
   den_clone7->SetPassedEvents(14,0);
   den_clone7->SetTotalEvents(15,0);
   den_clone7->SetPassedEvents(15,0);
   den_clone7->SetTotalEvents(16,0);
   den_clone7->SetPassedEvents(16,0);
   den_clone7->SetTotalEvents(17,0);
   den_clone7->SetPassedEvents(17,0);
   den_clone7->SetTotalEvents(18,0);
   den_clone7->SetPassedEvents(18,0);
   den_clone7->SetTotalEvents(19,0);
   den_clone7->SetPassedEvents(19,0);
   den_clone7->SetTotalEvents(20,0);
   den_clone7->SetPassedEvents(20,0);
   den_clone7->SetTotalEvents(21,0);
   den_clone7->SetPassedEvents(21,0);
   den_clone7->SetTotalEvents(22,0);
   den_clone7->SetPassedEvents(22,0);
   den_clone7->SetTotalEvents(23,0);
   den_clone7->SetPassedEvents(23,0);
   den_clone7->SetTotalEvents(24,0);
   den_clone7->SetPassedEvents(24,0);
   den_clone7->SetTotalEvents(25,0);
   den_clone7->SetPassedEvents(25,0);
   den_clone7->SetTotalEvents(26,0);
   den_clone7->SetPassedEvents(26,0);
   den_clone7->SetFillColor(19);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   den_clone7->SetLineColor(ci);
   den_clone7->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   den_clone7->SetMarkerColor(ci);
   den_clone7->SetMarkerStyle(21);
   den_clone7->Draw("same samep");
   
   TLegend *leg = new TLegend(0,0,0,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("den_clone","LCT","pl");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TText *text = new TText(0.17,0.17,"ME1/1");
   text->SetNDC();
   text->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
